# Generated by Django 2.1.7 on 2019-03-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='none', max_length=150)),
                ('robot_name', models.CharField(default='none', max_length=150)),
                ('auth', models.CharField(default='none', max_length=150)),
                ('ip', models.CharField(default='none', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('posx', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('posy', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('orientation', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('state1', models.CharField(default='none', max_length=150)),
                ('velocity_l', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('velocity_a', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('robot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='dashboard.Robot')),
            ],
        ),
    ]
