# Generated by Django 2.1.7 on 2019-03-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rstatus',
            old_name='state1',
            new_name='state',
        ),
    ]
