# Generated by Django 2.1.7 on 2019-03-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190314_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misson', models.CharField(max_length=150)),
                ('mision_state', models.CharField(max_length=150)),
                ('asigned_robot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_robot', to='dashboard.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mission', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
