# Generated by Django 2.1.7 on 2019-03-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mission_queue_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_queue',
            name='asigned_robot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_robot', to='dashboard.Robot'),
        ),
    ]
