# Generated by Django 2.1.7 on 2019-03-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190315_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission_queue',
            old_name='misson',
            new_name='mission',
        ),
    ]
