# Generated by Django 2.1.7 on 2019-03-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190315_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_queue',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission', to='dashboard.Missions'),
        ),
    ]
