# Generated by Django 2.1.7 on 2019-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190315_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_queue',
            name='mision_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='missions',
            name='id_mission',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='rstatus',
            name='state',
            field=models.IntegerField(),
        ),
    ]
