# Generated by Django 2.1.7 on 2019-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190319_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='time_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
