# Generated by Django 2.1.7 on 2019-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_missions_time_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='time_request',
        ),
        migrations.AddField(
            model_name='mission_queue',
            name='time_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
