# Generated by Django 2.1.7 on 2019-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190319_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
