# Generated by Django 2.1.7 on 2019-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_robot_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rstatus',
            name='statetext',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
