# Generated by Django 2.1.7 on 2019-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_mission_queue_robot_queue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_queue',
            name='robot_queue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
