# Generated by Django 2.1.7 on 2019-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190506_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolsBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='none', max_length=150)),
                ('verification', models.BooleanField(default=False)),
                ('SW1_mode', models.IntegerField()),
                ('SW1_state', models.BooleanField(default=False)),
            ],
        ),
    ]
