# Generated by Django 2.1.7 on 2019-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_golsbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='golsbox',
            name='SW2_mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW2_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW3_mode',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW3_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW4_mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW4_state',
            field=models.BooleanField(default=False),
        ),
    ]
