# Generated by Django 2.1.7 on 2019-05-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190507_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='golsbox',
            name='SW1_mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission1', to='dashboard.Missions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW2_mission',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission2', to='dashboard.Missions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW3_mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission3', to='dashboard.Missions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golsbox',
            name='SW4_mission',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission4', to='dashboard.Missions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW1_mode',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW2_mode',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW3_mode',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW4_mode',
            field=models.IntegerField(default=2),
        ),
    ]
