# Generated by Django 2.1.7 on 2019-05-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190507_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golsbox',
            name='SW1_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission1', to='dashboard.Missions'),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW2_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission2', to='dashboard.Missions'),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW3_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission3', to='dashboard.Missions'),
        ),
        migrations.AlterField(
            model_name='golsbox',
            name='SW4_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_mission4', to='dashboard.Missions'),
        ),
    ]
