# Generated by Django 2.1.7 on 2019-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190507_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='rstatus',
            name='mission_queue_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
